# Generated by Django 5.2 on 2025-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_feed',
            name='telemetry_battery_perc',
            field=models.FloatField(default=0),
        ),
    ]
