# Generated by Django 5.2 on 2025-04-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_feed_telemetry_battery_perc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location_feed',
            name='spd_mx',
        ),
        migrations.RemoveField(
            model_name='location_feed',
            name='spd_rd',
        ),
        migrations.RemoveField(
            model_name='location_feed',
            name='spd_src',
        ),
        migrations.RemoveField(
            model_name='location_feed',
            name='spd_un',
        ),
    ]
