# Generated by Django 5.2 on 2025-04-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_location_feed_spd_mx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location_feed',
            name='linked_id',
        ),
        migrations.RemoveField(
            model_name='location_feed',
            name='linked_name',
        ),
        migrations.RemoveField(
            model_name='location_feed',
            name='linked_type',
        ),
    ]
