# Generated by Django 5.2 on 2025-04-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_location_feed_linked_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_feed',
            name='date_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_feed',
            name='lastMovement_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_feed',
            name='received_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_feed',
            name='trip_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
