# Generated by Django 5.2 on 2025-04-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_location_feed_date_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_feed',
            name='trip_start',
            field=models.CharField(max_length=50),
        ),
    ]
