# Generated by Django 5.2 on 2025-04-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_location_feed_trip_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_feed',
            name='lastMovement_datetime',
            field=models.CharField(max_length=50),
        ),
    ]
