# Generated by Django 5.2.3 on 2025-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_location_feed_lastmovement_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_feed',
            name='driver_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location_feed',
            name='driver_name_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='location_feed',
            name='lastMovement_datetime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location_feed',
            name='object_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location_feed',
            name='trip_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
