# Generated by Django 5.2.3 on 2025-06-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_location_feed_driver_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location_feed',
            old_name='driver_name_datetime',
            new_name='driver_name_update_time',
        ),
    ]
