# Generated by Django 5.2.3 on 2025-06-18 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_driver_name_datetime_location_feed_driver_name_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_feed',
            name='driver_name_update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
