# Generated by Django 5.2.3 on 2025-06-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_location_feed_driver_name_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_feed',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
